[package]
name = "rust_hsm"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "1.0.51"
strum = { version = "0.26.3", features = ["derive"]}
log = "0.4.22"
tokio = { version = "1.45.1", features = ["sync", "macros", "rt"] }
