[package]
name = "rust_hsm"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "1.0.51"
strum = { version = "0.26.3", features = ["derive"]}
log = "0.4.22"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
